version: '3'
services:
  app1:
    image: app1:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
      args:
        app_name: app1
    ports:
    - "5001:5000"
  app2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
      args:
        app_name: app2
    ports:
    - "5002:5000"